version: "3.9"

services:
  postgres:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  # Development container
  dev: &dev
    build:
      context: .
      dockerfile: example_project/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    working_dir: /app/example_project
    tty: true
    stdin_open: true
    depends_on:
      - redis
    command: "/bin/bash"

  default_worker:
    <<: *dev
    tty: false
    ports: []
    command: celery -A example_project worker -l info

  email_worker:
    <<: *dev
    tty: false
    ports: []
    command: celery -A example_project worker -l info

  other_worker:
    <<: *dev
    tty: false
    ports: []
    command: celery -A example_project worker -l info

  beat:
    <<: *dev
    tty: false
    ports: []
    command: celery -A example_project beat -l info

  flower:
    <<: *dev
    ports:
      - "5555:5555"
    command: celery -A example_project flower --broker=redis://redis:6379/0
